# Generated by Django 5.2.3 on 2025-07-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='email',
            new_name='accesslevel',
        ),
        migrations.RenameField(
            model_name='registeruser',
            old_name='phoneno',
            new_name='username',
        ),
    ]
