# Generated by Django 5.2.3 on 2025-07-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('supplier', models.TextField()),
                ('qty', models.IntegerField()),
                ('cost', models.FloatField()),
                ('date', models.CharField(max_length=255)),
                ('staff', models.CharField(max_length=255)),
            ],
        ),
    ]
