# Generated by Django 5.2.4 on 2025-07-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
