# Generated by Django 5.2.4 on 2025-07-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_delete_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
