# Generated by Django 5.2.4 on 2025-07-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
