# Generated by Django 5.2.4 on 2025-07-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='selling',
            field=models.FloatField(default=0),
        ),
    ]
