# Generated by Django 5.2.4 on 2025-07-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_inventory_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='mop',
            field=models.CharField(default='', max_length=255),
        ),
    ]
